# agent-config.yaml

apiVersion: v1alpha1
kind: agentConfig #optional
metadata:
  name: oscp
rendezvousIP: 10.10.100.190 #bootstrap node
hosts:
  - hostname: assister-master-0 #master-0
    interfaces:
     - name: ens192
       macAddress: 00:50:56:b4:bc:be
    networkConfig:
      interfaces:
        - name: ens192
          type: ethernet
          state: up
          mac-address: 00:50:56:b4:bc:be
          ipv4:
            enabled: true
            address:
              - ip: 10.10.100.190 #master-0, here bootstrap and master0 same ip
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 10.10.100.150 #dns server
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.10.100.254 #route IP
            next-hop-interface: ens192
            table-id: 254
  - hostname: assister-master-1
    interfaces:
     - name: ens192
       macAddress: 00:50:56:b4:06:72
    networkConfig:
      interfaces:
        - name: ens192
          type: ethernet
          state: up
          mac-address: 00:50:56:b4:06:72
          ipv4:
            enabled: true
            address:
              - ip: 10.10.100.191
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 10.10.100.150
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.10.100.254
            next-hop-interface: ens192
            table-id: 254
  - hostname: assister-master-2
    interfaces:
     - name: ens192
       macAddress: 00:50:56:b4:ae:5c
    networkConfig:
      interfaces:
        - name: ens192
          type: ethernet
          state: up
          mac-address: 00:50:56:b4:ae:5c
          ipv4:
            enabled: true
            address:
              - ip: 10.10.100.192
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 10.10.100.150
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.10.100.254
            next-hop-interface: ens192
            table-id: 254



